### ISSUE TITLE
Can You Run Without app.listen()?

### ISSUE THREAD

**Issue by dschinkel** [zillow-oc/Koanect#1]
I've been trying to find a way to call functions that are bound to my app that I specified via app.use().  Reason being is I'm Test Driving the SUT code for my koa endpoints.  And so being unit tests (not integration, so not using something like supertest), I need to be able to hit an app instance without running app.listen() and be able to call those endpoints from code directly so I can verify my SUT code is working...

Later I will create integration tests that test from outside over the app running over the node http server instance but not there yet.  Right now I need to make sure my unit tests are unit tests, not integration tests and trying to figure out how you'd call your app instance's middleware or whatever you wanna call it...not sure the proper term for this.

**Comment by thecaddy** [comment]
Is there a reason you can't call listen?  Listen without passing in a port number will turn on your web server without binding to anything, really useful for testing.

You can see in the tests below using supertest calling the endpoints without having the server bound to a port.
https://github.com/zillow-oc/Koanect/blob/master/test/server.test.js

**Comment by dschinkel** [comment]
Because that would mean I'm testing over a real web server.  I am not integration testing here.  I am testing the contract of my API.  That means I do not want my tests hitting stuff like an http server...my unit tests that is, my BDD unit tests that drive me to create that very code!  I can't be testing over real stuff, it has to be isolated..mocked or in my case I'm just trying to call the app's route directly so I can verify request input/output at the server-side (nothing is running, I'm testing my Service Contract code).  I don't want to be invoking app.listen().  That's fine if you wanna integration test and use supertest over a real web service to test the API after to test a bit of integration.

**Comment by thecaddy** [comment]
.listen() without a port is actually a mock of the http server.  I don't know how you would mock so you can hit your endpoints independently to test your api without it because it handles the http spec of headers, formatting, netotiation, etc...

If you really want to avoid .listen() you could always set up a separate method called by the endpoint and test that method independent of the endpoint.

**Comment by dschinkel** [comment]
oh I wasn't aware that it was a mock without a port but I guess that makes
sense, it can't create a server if it has no port!  thanks

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dave Schinkel
Sr. C# Software Engineer
LinkedIn Profile <http://www.linkedin.com/in/daveschinkel>

*Remember, Don't Text and Drive! *
*http://bit.ly/1tenq5O <http://bit.ly/1tenq5O>, http://bit.ly/1jXXRN0
<http://bit.ly/1jXXRN0>, http://bit.ly/1rFCtne <http://bit.ly/1rFCtne>*

On Fri, Jul 17, 2015 at 11:10 AM, Joel Trost <notifications@github.com>
wrote:

> .listen() without a port is actually a mock of the http server. I don't
> know how you would mock so you can hit your endpoints independently to test
> your api without it because it handles the http spec of headers,
> formatting, netotiation, etc...
>
> If you really want to avoid .listen() you could always set up a separate
> method called by the endpoint and test that method independent of the
> endpoint.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zillow-oc/Koanect/issues/1#issuecomment-122329116>.
>

**Comment by dschinkel** [comment]
weird, this one is using a port https://github.com/koajs/mock

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dave Schinkel
Sr. C# Software Engineer
LinkedIn Profile <http://www.linkedin.com/in/daveschinkel>

*Remember, Don't Text and Drive! *
*http://bit.ly/1tenq5O <http://bit.ly/1tenq5O>, http://bit.ly/1jXXRN0
<http://bit.ly/1jXXRN0>, http://bit.ly/1rFCtne <http://bit.ly/1rFCtne>*

On Fri, Jul 17, 2015 at 11:12 AM, dschinkel <dschinkel@gmail.com> wrote:

> oh I wasn't aware that it was a mock without a port but I guess that makes
> sense, it can't create a server if it has no port!  thanks
>
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> Dave Schinkel
> Sr. C# Software Engineer
> LinkedIn Profile <http://www.linkedin.com/in/daveschinkel>
>
> *Remember, Don't Text and Drive! *
> *http://bit.ly/1tenq5O <http://bit.ly/1tenq5O>, http://bit.ly/1jXXRN0
> <http://bit.ly/1jXXRN0>, http://bit.ly/1rFCtne <http://bit.ly/1rFCtne>*
>
> On Fri, Jul 17, 2015 at 11:10 AM, Joel Trost <notifications@github.com>
> wrote:
>
>> .listen() without a port is actually a mock of the http server. I don't
>> know how you would mock so you can hit your endpoints independently to test
>> your api without it because it handles the http spec of headers,
>> formatting, netotiation, etc...
>>
>> If you really want to avoid .listen() you could always set up a separate
>> method called by the endpoint and test that method independent of the
>> endpoint.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/zillow-oc/Koanect/issues/1#issuecomment-122329116>.
>>
>
>

**Comment by thecaddy** [comment]
This looks like a website mock not server mock.

**Comment by dschinkel** [comment]
I don't want to mock the app actually now that I think about it.  I'm testing and building out the SUT which is the service I'm building so I don't wanna mock the service.  What I am trying to do is simply call the code I create without starting the web service.  Maybe what I am leading myself to is to mock the request and to send that mock request to an app.routes.get call (but that the server isn't started up...no .listen())...just thinking about it a little.  The point is I'm test driving my koa endpoint and I want to make calls to the endpoint I create but do not want the web server started is what I'm getting at.

**Comment by dschinkel** [comment]
nevermind, supertest I thought relied on app.listen() but it says it's for testing lower level requests right in the docs duh!  Using supertest.
